{
  "openapi" : "3.0.3",
  "info" : {
    "title" : "ChatSphere API",
    "description" : "API for ChatSphere, a real-time chat application.",
    "contact" : {
      "name" : "ChatSphere Support",
      "url" : "https://your-api-server.com/support",
      "email" : "support@chatsphere.com"
    },
    "license" : {
      "name" : "MIT",
      "url" : "https://opensource.org/licenses/MIT"
    },
    "version" : "1.0.0"
  },
  "servers" : [ {
    "url" : "https://virtserver.swaggerhub.com/YINKAWLB/chatterbox1/1.0.0",
    "description" : "SwaggerHub API Auto Mocking"
  }, {
    "url" : "https://your-api-server.com/api",
    "description" : "Production Server"
  } ],
  "paths" : {
    "/auth/login" : {
      "post" : {
        "summary" : "User Login.",
        "description" : "Authenticate a user and retrieve a token.",
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/auth_login_body"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "Successful login",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/inline_response_200"
                }
              }
            }
          },
          "default" : {
            "description" : "Unexpected error",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/ErrorResponse"
                }
              }
            }
          }
        }
      }
    },
    "/auth/register" : {
      "post" : {
        "summary" : "User Registration.",
        "description" : "Register a new user.",
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/auth_register_body"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "201" : {
            "description" : "User registered successfully",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/User"
                }
              }
            }
          },
          "400" : {
            "description" : "Bad request",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "default" : {
            "description" : "Unexpected error",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/ErrorResponse"
                }
              }
            }
          }
        }
      }
    },
    "/user/{id}/profile" : {
      "get" : {
        "summary" : "Get User Profile.",
        "description" : "Retrieve user profile data.",
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "description" : "User ID",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "User profile retrieved",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/User"
                }
              }
            }
          },
          "404" : {
            "description" : "User not found",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "default" : {
            "description" : "Unexpected error",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/ErrorResponse"
                }
              }
            }
          }
        },
        "security" : [ {
          "bearerAuth" : [ ]
        } ]
      }
    },
    "/chat/send" : {
      "post" : {
        "summary" : "Send Message.",
        "description" : "Send a chat message to a user or group.",
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/chat_send_body"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "Message sent successfully",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/inline_response_200_1"
                }
              }
            }
          },
          "400" : {
            "description" : "Bad request",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "default" : {
            "description" : "Unexpected error",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/ErrorResponse"
                }
              }
            }
          }
        },
        "security" : [ {
          "bearerAuth" : [ ]
        } ]
      }
    },
    "/upload" : {
      "post" : {
        "summary" : "Upload Profile Picture.",
        "description" : "Upload a profile picture or status image.",
        "requestBody" : {
          "content" : {
            "multipart/form-data" : {
              "schema" : {
                "$ref" : "#/components/schemas/upload_body"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "Image uploaded successfully",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/inline_response_200_2"
                }
              }
            }
          },
          "default" : {
            "description" : "Unexpected error",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/ErrorResponse"
                }
              }
            }
          }
        },
        "security" : [ {
          "bearerAuth" : [ ]
        } ]
      }
    },
    "/geo/share" : {
      "post" : {
        "summary" : "Share Location.",
        "description" : "Share the user's geolocation.",
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/geo_share_body"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "Location shared successfully",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/inline_response_200_3"
                }
              }
            }
          },
          "default" : {
            "description" : "Unexpected error",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/ErrorResponse"
                }
              }
            }
          }
        },
        "security" : [ {
          "bearerAuth" : [ ]
        } ]
      }
    }
  },
  "components" : {
    "schemas" : {
      "User" : {
        "required" : [ "email", "id", "name" ],
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "string",
            "example" : "12345"
          },
          "name" : {
            "type" : "string",
            "example" : "John Doe"
          },
          "email" : {
            "type" : "string",
            "format" : "email",
            "example" : "user@example.com"
          }
        }
      },
      "ErrorResponse" : {
        "required" : [ "error" ],
        "type" : "object",
        "properties" : {
          "error" : {
            "type" : "string",
            "example" : "Resource not found"
          }
        }
      },
      "auth_login_body" : {
        "required" : [ "email", "password" ],
        "type" : "object",
        "properties" : {
          "email" : {
            "type" : "string",
            "format" : "email",
            "example" : "user@example.com"
          },
          "password" : {
            "type" : "string",
            "example" : "yourPassword123"
          }
        }
      },
      "inline_response_200" : {
        "type" : "object",
        "properties" : {
          "token" : {
            "type" : "string",
            "example" : "JWT_TOKEN"
          },
          "user" : {
            "$ref" : "#/components/schemas/User"
          }
        }
      },
      "auth_register_body" : {
        "required" : [ "email", "name", "password" ],
        "type" : "object",
        "properties" : {
          "name" : {
            "type" : "string",
            "example" : "John Doe"
          },
          "email" : {
            "type" : "string",
            "format" : "email",
            "example" : "user@example.com"
          },
          "password" : {
            "type" : "string",
            "example" : "yourPassword123"
          }
        }
      },
      "chat_send_body" : {
        "required" : [ "message", "to" ],
        "type" : "object",
        "properties" : {
          "to" : {
            "type" : "string",
            "example" : "USER_OR_GROUP_ID"
          },
          "message" : {
            "type" : "string",
            "example" : "Hello!"
          }
        }
      },
      "inline_response_200_1" : {
        "type" : "object",
        "properties" : {
          "message" : {
            "type" : "string",
            "example" : "Message sent successfully"
          }
        }
      },
      "upload_body" : {
        "required" : [ "image" ],
        "type" : "object",
        "properties" : {
          "image" : {
            "type" : "string",
            "format" : "binary"
          }
        }
      },
      "inline_response_200_2" : {
        "type" : "object",
        "properties" : {
          "message" : {
            "type" : "string",
            "example" : "Image uploaded successfully"
          },
          "imageUrl" : {
            "type" : "string",
            "example" : "URL_TO_UPLOADED_IMAGE"
          }
        }
      },
      "geoshare_location" : {
        "required" : [ "latitude", "longitude" ],
        "type" : "object",
        "properties" : {
          "latitude" : {
            "type" : "number",
            "example" : 12.345678
          },
          "longitude" : {
            "type" : "number",
            "example" : 98.765432
          }
        }
      },
      "geo_share_body" : {
        "required" : [ "location", "userId" ],
        "type" : "object",
        "properties" : {
          "userId" : {
            "type" : "string",
            "example" : "USER_ID"
          },
          "location" : {
            "$ref" : "#/components/schemas/geoshare_location"
          }
        }
      },
      "inline_response_200_3" : {
        "type" : "object",
        "properties" : {
          "message" : {
            "type" : "string",
            "example" : "Location shared successfully"
          }
        }
      }
    },
    "securitySchemes" : {
      "bearerAuth" : {
        "type" : "http",
        "scheme" : "bearer",
        "bearerFormat" : "JWT"
      }
    }
  }
}